#!/usr/bin/php
<?php
//Linux cli PHP-script to format MAC-addresses
//Can be called with only MAC-address as argument or with extra second "dhcp" argument to format the MAC-address as the way MS-DHCP wants it to be.
//If called with no arguments it displays some basic instructions how to use the script
//Requires php-cli php-curl

function fix_mac($inputmac) {
	$inputmac=trim($inputmac);
	$inputmac=str_replace("o", "0", $inputmac);
	$inputmac=str_replace("O", "0", $inputmac);
	$inputmac=str_replace(".", ":", $inputmac);
	$inputmac=str_replace("s", "5", $inputmac);
	$inputmac=str_replace("S", "5", $inputmac);
	$inputmac=str_replace("l", "1", $inputmac);
	$inputmac=str_replace("L", "1", $inputmac);
	$inputmac=strtoupper($inputmac);
	$inputmac=str_replace(":", "", $inputmac);
	$inputmac=str_replace("-", "", $inputmac);
	$nokolonmac=$inputmac;
	$oct1=substr($nokolonmac, -12, 2);
	$oct2=substr($nokolonmac, -10, 2);
	$oct3=substr($nokolonmac, -8, 2);
	$oct4=substr($nokolonmac, -6, 2);
	$oct5=substr($nokolonmac, -4, 2);
	$oct6=substr($nokolonmac, -2, 2);
	$kolonmac=$oct1 . ':' . $oct2 . ':' . $oct3 . ':' . $oct4 . ':' . $oct5 . ':' . $oct6;
	return $kolonmac;
}

function dhcp_mac($inputmac) {
	$nokolonmac=str_replace(":", "", fix_mac($inputmac));
	return $nokolonmac;
}

function check_mac($inputmac) {
	$kolonmac=fix_mac($inputmac);
	if(preg_match('/^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$/', $kolonmac) && strlen(dhcp_mac($kolonmac)) == 12) {
		return TRUE;
	} else {
		return FALSE;
	}
}

function getvendorfrommac($mac) {
	$url = "http://api.macvendors.com/" . urlencode($mac);
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	$response = curl_exec($ch);
	if($response) {
		$vendor = $response;
	} else {
		$vendor = "N/A";
	}
	if(strpos($vendor,"Vendor not found") !== false) {
		$vendor = "N/A";
	}
	return $vendor;
}

function scriptname($commandargument) {
	$scriptstart = strrpos($commandargument, "/");
	$scriptstart++;
	$scriptname = substr($commandargument, $scriptstart, strlen($commandargument));
	return $scriptname;
}

if($argc > 1) {
	if( check_mac($argv[1]) ) {
		if($argc > 2) {
			if($argv[2] == "dhcp") {
				$outputmac = dhcp_mac($argv[1]);
			} else {
				$outputmac = fix_mac($argv[1]);
			}
		} else {
			$outputmac = fix_mac($argv[1]);
		}
		$vendor = getvendorfrommac(fix_mac($argv[1]));
		echo "MAC: $outputmac\n";
		echo "Vendor: $vendor\n";
	} else {
		echo "Invalid MAC-address!\n";
	}
} else {
	$scriptname = scriptname($argv[0]);
	echo "Usage: $scriptname <mac-address>\n";
	echo "Optional: $scriptname <mac-address> dhcp\n";
}
?>
